stages:
    - build

gcc:
  stage: build
  before_script:
    - echo "LAMA Version:" && file ${SCAI_ROOT}/lib/libscai_lama.so | sed 's/.*libscai_lama\.so\.\([0-9]*\.[0-9]*\.[0.9]*\).*/\1/g'
  script:
    - echo "g++ Version:" && g++ --version

