stages:
    - build
    - unittest
    - inversion

gcc:
  stage: build
  before_script:
     - git clone https://github.com/WAVE-Toolbox/WAVE-Simulation.git && cd WAVE-Simulation
     - git checkout 066e7c39c903edab37e56263
     - mkdir build && cd "$_"
     - SCAI_DIR=/data14/software/scai_lama/build_dev/ cmake ../src -DCMAKE_INSTALL_PREFIX=./
     - make install -j 4
     - cd ../../
  script:
    - echo "g++ Version:" && g++ --version
    - mkdir build && cd "$_"
    - Simulation_DIR=../WAVE-Simulation/build cmake ../src/ -DCMAKE_INSTALL_PREFIX=./
    - make install -j 4
  artifacts:
    when: on_success
    expire_in: 30 min
    paths:
    - build/bin/

unittest-gcc:
  stage: unittest
  script:
    - cd par/    
    - ./../build/bin/Test_unit

    
acoustic2D-gcc:
  stage: inversion
  script:
    - OMP_NUM_THREADS=1
    - cd par/
    - mpirun -np 4 ./../build/bin/Inversion "ci/configuration_ci.2D.acoustic.txt"
    - ./../build/bin/Test_integration "ci/configuration_ci.2D.acoustic.txt"


